### ISSUE TITLE
Issue when Importing SoftRes.It List

### ISSUE THREAD

**Issue by Gogo1951** [Gogo1951/GogoLoot#38]
![image](https://user-images.githubusercontent.com/55365231/104829063-830b5100-5835-11eb-9899-b2d1c8893e9e.png)

Code Imported
> eNqdl01v2kAQhv8K8pkD2IAhNwJNony0UYLUL+Ww2AOest4hu946TtT/3qWHFlV5o26FuHh5tON5Z94ZXhIuk5Mkn01H4ZuPx8Msm45m+SDpJ2xco0xB4Vw9jg5PnGwaS47sd3LJydeXhBuqk5N0OBlO+4kVrU/F+HA06CdG1QfyvlauWltxATfSHB4lP/rH5BiQS2/WCmLjAcBWyu4EUQMYZivrtSbAjacTxFWkNSNuMskQ50rbVijOfDAE3GkIkywbRKYpIm/UrpHWvM5l4xzl81yaoKA00Rfe7ys2hYu+8KKrOqgDKpa5DmkREx3krbK2iw5xyU9MTUUlqRJJD+Ezb7vn16nBLEUFurCKt69TaZ7BZqBSnPIW5SXLAXjXiX8C1DSbAepLt69EdzBMpMJCdMlmG636quXnhsto7lS2pTKy2US/4TvmaOZGrLRkFKqUFFuZJkjlyFpW/qlWBuYEYZeqVVbBQkkB9p6K8JwLFOYM3bdQdi1m42H/vZVRZbY72oekbqMre/5dkY1upA+2INdY1VD0aLn2BZOB4HiWQ/k5YEfVvVCmFybyrte0YTb/FTkS6LM3wRmj/ebW1/suehwuiW1p8RhFBvARtdUbklx5rY/r/Iwt9dj1NG/oH6WZ26JictFX3z96dlW3UfE+fm79rmklus8+kRHHLr7cyXbOwQ5D2BVrTTa0mf+PAe5NU4dwW3TrcIQ9wUQvfHOtarUDQuTpBLryN6kFYsh6Vmx2QPXhMEMvtqq8KVX0lngXdi82XMTb8m1YveAahbGlMowtDg6qu+CNYWGwTryOhi/9mjVRdGVfi9R7F71BX8iW4vfLRSVF+BxzD/2kUge3+/1/6OHPaT8p2RViy18//QmeEA/F

From this URL
> https://softres.it/raid/798479875513384970

Expectation

{rt4} GogoLoot : Softres.it List Imported! {#} Reserves across {#} Items included.
{rt4} GogoLoot : Softres.it URL https://softres.it/raid/{ID} 

Also need to make sure we're including the Discord link if it was set.

**Comment by AeroScripts** [comment]
Hmm, did you have the softres checkbox ticked? The announce only happens if you do

That debugging message happens regardless though, ill remove it

**Comment by AeroScripts** [comment]
Fixed with next release

**Comment by Gogo1951** [comment]
Still not outputting URL for SR raid.

![image](https://user-images.githubusercontent.com/55365231/105126857-3f1e8300-5aa5-11eb-9d2e-bcd06ce61f8c.png)
